services:
  api:
    image: ${API_IMAGE}
    container_name: auto-api
    ports:
      - "${API_PORT}:80"
    networks:
      - external
      - internal
    env_file: api-server/.env
    environment:
      - APP_ENV=PRODUCTION
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_ROOT_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_CHARSET=utf8

  web:
    image: ${WEB_IMAGE}
    container_name: auto-web
    ports:
      - "${APP_PORT}:80"
    networks:
      - external
    env_file: web/.env

  database:
    image: mysql
    container_name: auto-database
    env_file:
      - .env
    volumes:
      - auto-database_data:/var/lib/mysql
    networks:
      - internal

networks:
  external:
    external: true
    name: external
  internal:
    driver: bridge
    internal: true
    attachable: false

volumes:
  auto-database_data: